version: "3"

services:
  # setting for phoenix
  backend:
    build:
      context: phoenix
      dockerfile: Dockerfile
    volumes:
      - "./phoenix:/app/backend"
    container_name: phoenix_server
    ports:
      - "8080:4000"
    tty: true
    working_dir: "/app/backend"
    command: ash -c "mix deps.get && mix phx.server"
    depends_on:
      - db

  # setting for postgres
  db:
    image: postgres:12.0
    container_name: postgres_for_phoenix
    tty: true
    volumes:
      - "./postgres/lib:/var/lib/postgres"
    # set env values for local postgres
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root_password
      - POSTGRES_INITDB_ARGS="--encoding=UTF-8"
      - POSTGRES_HOST=db
    ports:
      - "5432:5432"